# Generated by Django 5.2.17 on 2026-10-05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DrugLabelInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("set_id", models.CharField(max_length=128)),
                ("version", models.CharField(max_length=64)),
                ("effective_time", models.CharField(blank=True, max_length=64)),
                ("brand_name", models.CharField(blank=True, max_length=512)),
                ("generic_name", models.CharField(blank=True, max_length=512)),
                ("substance_names", models.JSONField(default=list)),
                ("interaction_text", models.TextField()),
                ("source_url", models.URLField(max_length=2048)),
                ("source_hash", models.CharField(max_length=64)),
                ("imported_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("set_id", "version"),
                        name="drug_label_interaction_set_id_version_uniq",
                    )
                ]
            },
        )
    ]
